const csh = {
  CurrentDir: '%~',
  FullNameOfDir: '%/',
  BaseNameOfDIr: '%c',
  FullHostName: '%M',
  FQDNHostName: '%m',
  NameOfShell: '%l',
  TheDate: '',
  Time24: '%T',
  TIme12: '%t',
  UsrName: '%n',
};
const bash = {
  CurrentDir: '%~',
  FullNameOfDir: '%/',
  BaseNameOfDIr: '%c',
  FullHostName: '%M',
  FQDNHostName: '%m',
  NameOfShell: '%l',
  TheDate: '',
  Time24: '%T',
  TIme12: '%t',
  UsrName: '%n',
};
const zsh = {
  CurrentDir: '%~',
  FullNameOfDir: '%/',
  BaseNameOfDIr: '%c',
  FullHostName: '%M',
  FQDNHostName: '%m',
  NameOfShell: '%l',
  TheDate: '',
  Time24: '%T',
  TIme12: '%t',
  UsrName: '%n',
};
const ksh = {
  CurrentDir: '%~',
  FullNameOfDir: '%/',
  BaseNameOfDIr: '%c',
  FullHostName: '%M',
  FQDNHostName: '%m',
  NameOfShell: '%l',
  TheDate: '',
  Time24: '%T',
  TIme12: '%t',
  UsrName: '%n',
};
