const ADDNEWELEM = "RESULT/MOFIFY/ADD_NEW_PROMPT_ELEMENT"
const ADDNEWLINE = "RESULT/MODIFY/ADD_NEW_LINE"
const REMOVELINE = "RESULT/MODIFY/DELETE_CURRENT_LINE"
const UPDATESELECTEDELEM = "RESULT/MODIFY/UPDATE_SELECTED_ELEMENT"
const DELETESELECTRD = "RESULT/MODIFY/DELETE_SELECTED_ELEMENT"
const MOVEBACK = "RESULT/MOVE_ELEMENT_BACK"
const MOVEFORWARD = "RESULT/MOVE_ELEMENT_FORWARD"

export default {
  ADDNEWELEM, ADDNEWLINE, REMOVELINE, UPDATESELECTEDELEM, DELETESELECTRD,
  MOVEFORWARD, MOVEBACK
}