// stylize
const CHANGETEXT = "PSONE/STYLE/CHANGE_CUSTOM_TEXT"
const SETFGCOLOR = "PSONE/STYLE/SET_FG_COLOR"
const SETBGCOLOR = "PSONE/STYLE/SET_BG_COLOR"
const SETTEXTDECOR = "PSONE/STYLE/SET_TEXT_STYLE"
const REMOVETEXTDECOR = "PSONE/STYLE/REMOVE_TEXT_STYLE"
// modify
const SETCURELEM = "PSONE/MODIFY/SET_CURRENT_ELEMENT"
const UPDATECURELEM = "PSONE/MODIFY/UPDATE_CURRENT_ELEMENT"
const SETLINE = "PSONE/MODIFY/SELECT_LINE"
const SETELEMTOINIT = "PSONE/APP/SET_ELEMENT_TO_INITIAL"

const CHANGEMODSTATUS = "PSONE/APP/CHANGE_EDIT_MOD_STATUS"
const OPENCONTROL = "PSONE/APP/LM/OPEN_CURRENT_CONTROL"
const CLOSECONTROL = "PSONE/APP/LM/CLOSE_CURRENT_CONTROL"
const CLOSEALLCONTROLS = "PSONE/APP/LM/CLOSE_ALL_CONTROLS"


export default {
  CHANGETEXT, SETFGCOLOR, SETBGCOLOR, SETTEXTDECOR, REMOVETEXTDECOR, SETCURELEM,
  UPDATECURELEM, SETLINE, CHANGEMODSTATUS, SETELEMTOINIT, OPENCONTROL, CLOSECONTROL,
  CLOSEALLCONTROLS
}