// PSONE OPTIONS TYPES
// stylize
export const CHANGETEXT = "PSONE/STYLE/CHANGE_CUSTOM_TEXT"
export const SETFGCOLOR = "PSONE/STYLE/SET_FG_COLOR"
export const SETBGCOLOR = "PSONE/STYLE/SET_BG_COLOR"
export const SETTEXTDECOR = "PSONE/STYLE/SET_TEXT_STYLE"
export const REMOVETEXTDECOR = "PSONE/STYLE/REMOVE_TEXT_STYLE"
// modify
export const SETCURELEM = "PSONE/MODIFY/SET_CURRENT_ELEMENT"
export const UPDATECURELEM = "PSONE/MODIFY/UPDATE_CURRENT_ELEMENT"
export const SETLINE = "PSONE/MODIFY/SELECT_LINE"
// App status
export const CHANGEMODSTATUS = "PSONE/APP/CHANGE_EDIT_MOD_STATUS"
export const SETELEMTOINIT = "PSONE/APP/SET_ELEMENT_TO_INITIAL"
export const OPENCONTROL = "PSONE/APP/LM/OPEN_CURRENT_CONTROL"
export const CLOSECONTROL = "PSONE/APP/LM/CLOSE_CURRENT_CONTROL"
export const CLOSEALLCONTROLS = "PSONE/APP/LM/CLOSE_ALL_CONTROLS"
