// PSONE OPTIONS TYPES
// stylize
export const CHANGETEXT = "PSONE/STYLE/CHANGE_CUSTOM_TEXT"
export const SETFGCOLOR = "PSONE/STYLE/SET_FG_COLOR"
export const SETBGCOLOR = "PSONE/STYLE/SET_BG_COLOR"
export const SETTEXTDECOR = "PSONE/STYLE/SET_TEXT_STYLE"
export const REMOVETEXTDECOR = "PSONE/STYLE/REMOVE_TEXT_STYLE"
// modify
export const SETCURELEM = "PSONE/MODIFY/SET_CURRENT_ELEMENT"
export const UPDATECURELEM = "PSONE/MODIFY/UPDATE_CURRENT_ELEMENT"
export const SETLINE = "PSONE/MODIFY/SELECT_LINE"
// App status
export const CHANGEMODSTATUS = "PSONE/APP/CHANGE_EDIT_MOD_STATUS"
export const SETELEMTOINIT = "PSONE/APP/SET_ELEMENT_TO_INITIAL"
export const OPENCONTROL = "PSONE/APP/LM/OPEN_CURRENT_CONTROL"
export const CLOSECONTROL = "PSONE/APP/LM/CLOSE_CURRENT_CONTROL"
export const CLOSEALLCONTROLS = "PSONE/APP/LM/CLOSE_ALL_CONTROLS"
// RESULT TYPES
export const ADDNEWELEM = "RESULT/MOFIFY/ADD_NEW_PROMPT_ELEMENT"
export const ADDNEWLINE = "RESULT/MODIFY/ADD_NEW_LINE"
export const REMOVELINE = "RESULT/MODIFY/DELETE_CURRENT_LINE"
export const UPDATESELECTEDELEM = "RESULT/MODIFY/UPDATE_SELECTED_ELEMENT"
export const DELETESELECTRD = "RESULT/MODIFY/DELETE_SELECTED_ELEMENT"
export const MOVEFORWARD = "RESULT/MOVE_ELEMENT_FORWARD"
export const MOVEBACK = "RESULT/MOVE_ELEMENT_BACK"