export const psOneSequences = [
  {
    text: "The hostname (short)",
    sequences: "LocalHost",
    code: "\\h",
    bg: "",
    fg: "",
  },
  {
    text: "The base name of term",
    sequences: "ttys001",
    code: "\\l",
    bg: "",
    fg: "",
  },
  {
    text: "The name of shell",
    sequences: "bash",
    code: "\\s",
    bg: "",
    fg: "",
  },
  {
    text: "The current time",
    sequences: "16:00:03",
    code: "\\t",
    bg: "",
    fg: "",
  },
  {
    text: "The username",
    sequences: "EgorL",
    code: "\\u",
    bg: "",
    fg: "",
  },
  {
    text: "The version of shell",
    sequences: "3.2",
    code: "\\v",
    bg: "",
    fg: "",
  },
  {
    text: "The version of shell",
    sequences: "3.2",
    code: "\\v",
    bg: "",
    fg: "",
  },
  {
    text: "The version of shell",
    sequences: "3.2",
    code: "\\v",
    bg: "",
    fg: "",
  },
  {
    text: "space",
    sequences: " ",
    code: "\\v",
    bg: "",
    fg: "",
  },
];
