let initialState = {
  items: [
    {
      id: 1,
      text: "The hostname (short)",
      sequences: "LocalHost",
      code: "\\h",
      bg: "",
      fg: "",
    },
    {
      id: 2,
      text: "The base name of term",
      sequences: "ttys001",
      code: "\\l",
      bg: "",
      fg: "",
    },
    {
      id: 3,
      text: "The name of shell",
      sequences: "bash",
      code: "\\s",
      bg: "",
      fg: "",
    },
    {
      id: 4,
      text: "The current time",
      sequences: "16:00:03",
      code: "\\t",
      bg: "",
      fg: "",
    },
    {
      id: 5,
      text: "The username",
      sequences: "EgorL",
      code: "\\u",
      bg: "",
      fg: "",
    },
    {
      id: 6,
      text: "The version of shell",
      sequences: "3.2",
      code: "\\v",
      bg: "",
      fg: "",
    },
    {
      id: 7,
      text: "The version of shell",
      sequences: "3.2",
      code: "\\v",
      bg: "",
      fg: "",
    },
    {
      id: 8,
      text: "The version of shell",
      sequences: "3.2",
      code: "\\v",
      bg: "",
      fg: "",
    },
    {
      id: 9,
      text: "space space space",
      sequences: " ",
      code: "\\v",
      bg: "",
      fg: "",
    },
  ],
  ok: "immutablility",
};
