const CHANGEMODSTATUS = "PSONE/APP/CHANGE_EDIT_MOD_STATUS"
const SETELEMTOINIT = "PSONE/APP/SET_ELEMENT_TO_INITIAL"
const OPENCONTROL = "PSONE/APP/LM/OPEN_CURRENT_CONTROL"
const CLOSECONTROL = "PSONE/APP/LM/CLOSE_CURRENT_CONTROL"
const CLOSEALLCONTROLS = "PSONE/APP/LM/CLOSE_ALL_CONTROLS"

const CHANGELOADSTATUS = "CONDITION/APP/CHANGE_LOADING_STATUS"

export default {
  CHANGEMODSTATUS, SETELEMTOINIT, OPENCONTROL, CLOSECONTROL, CLOSEALLCONTROLS,
  CHANGELOADSTATUS
}